/*
 * BetMonitor for generating matches and Odds
 *
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A request body of a wager placed by a user on a marketState.
    /// </summary>
    [DataContract(Name = "bet-place-dto")]
    public partial class BetPlaceDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BetPlaceDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BetPlaceDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BetPlaceDto" /> class.
        /// </summary>
        /// <param name="stake">stake (required).</param>
        public BetPlaceDto(int stake = default(int))
        {
            this.Stake = stake;
        }

        /// <summary>
        /// Gets or Sets Stake
        /// </summary>
        [DataMember(Name = "stake", IsRequired = true, EmitDefaultValue = true)]
        public int Stake { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BetPlaceDto {\n");
            sb.Append("  Stake: ").Append(Stake).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Stake (int) minimum
            if (this.Stake < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Stake, must be a value greater than or equal to 0.", new [] { "Stake" });
            }

            yield break;
        }
    }

}
