/*
 * BetMonitor for generating matches and Odds
 *
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines bet-status-dto
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BetStatusDto
    {
        /// <summary>
        /// Enum WIN for value: WIN
        /// </summary>
        [EnumMember(Value = "WIN")]
        WIN = 1,

        /// <summary>
        /// Enum LOSS for value: LOSS
        /// </summary>
        [EnumMember(Value = "LOSS")]
        LOSS = 2,

        /// <summary>
        /// Enum PENDING for value: PENDING
        /// </summary>
        [EnumMember(Value = "PENDING")]
        PENDING = 3,

        /// <summary>
        /// Enum VOID for value: VOID
        /// </summary>
        [EnumMember(Value = "VOID")]
        VOID = 4
    }

}
