version: "3"
services:
  bmon-oddsgen:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "8.0-bookworm"
    volumes:
      # figure out why /obj folders keep reverting to root:root, root group and tmpfs combo issue?
      - .:/workspace
      - type: tmpfs
        target: /tmp
      - "oddsgen-workspace-main-bin:/workspace/src/Org.BmonOddsGen/bin/"
      - "oddsgen-workspace-openapi-bin:/workspace/src/Org.OpenAPITools/bin/"
      - "oddsgen-workspace-test-bin:/workspace/src/Org.BmonOddsGen.Test/bin/"
      - "oddsgen-workspace-main-obj:/workspace/src/Org.BmonOddsGen/obj/"
      - "oddsgen-workspace-openapi-obj:/workspace/src/Org.OpenAPITools/obj/"
      - "oddsgen-workspace-test-obj:/workspace/src/Org.BmonOddsGen.Test/obj/"

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - main
    ports:
      - "8081:8081"
    external_links:
      - postgres

volumes:
  "oddsgen-workspace-main-bin":
  "oddsgen-workspace-openapi-bin":
  "oddsgen-workspace-test-bin":
  "oddsgen-workspace-main-obj":
  "oddsgen-workspace-openapi-obj":
  "oddsgen-workspace-test-obj":

networks:
  main:
    external:
      name: bmon-odds-server_main
